-- CreateEnum: All application enums
-- These are shared across multiple entities

CREATE TYPE "public"."Role" AS ENUM ('SUPER_ADMIN', 'MANAGER', 'CASHIER');

CREATE TYPE "public"."UserStatus" AS ENUM ('ACTIVE', 'INACTIVE');

CREATE TYPE "public"."ProductCategory" AS ENUM ('FOOD_AND_BEVERAGES', 'HOUSEHOLD_ITEMS', 'HEALTH_AND_BEAUTY', 'CLOTHING_AND_APPAREL', 'ELECTRONICS', 'TOYS_AND_GAMES', 'OFFICE_SUPPLIES', 'PET_SUPPLIES', 'AUTOMOTIVE', 'BOOKS_AND_STATIONERY', 'SEASONAL_AND_SPECIAL_OCCASIONS', 'BABY_PRODUCTS', 'SPORTS_AND_OUTDOORS', 'MEDIA', 'OFFICE_AND_SCHOOL_SUPPLIES', 'GARDENING_AND_TOOLS', 'JEWELRY_AND_WATCHES', 'HEALTH_AND_FITNESS', 'OTHERS');

CREATE TYPE "public"."PaymentMode" AS ENUM ('CASH', 'CARD', 'BANK_TRANSFER', 'CRYPTO', 'OTHER');

CREATE TYPE "public"."DeshelvingReason" AS ENUM ('DAMAGED', 'RETURNED', 'EXPIRED', 'RESERVED', 'STOLEN', 'LOST', 'QUALITY_CONTROL', 'RECALL', 'TRANSFER', 'OTHER');
