#!/bin/bash
# Install pgBackRest in PostgreSQL container
# This script runs during container initialization

set -e

echo "Configuring pgBackRest in PostgreSQL container..."

# Create necessary directories
mkdir -p /var/lib/pgbackrest \
         /var/log/pgbackrest \
         /var/spool/pgbackrest

# Set permissions
chown -R postgres:postgres /var/lib/pgbackrest \
                          /var/log/pgbackrest \
                          /var/spool/pgbackrest

# Link our mounted config to /etc/pgbackrest
echo "Linking pgBackRest configuration from shared volume..."
rm -rf /etc/pgbackrest
ln -s /pgbackrest-config /etc/pgbackrest

# Check if backups are disabled
if [ "${PGBACKREST_REPO1_TYPE:-none}" = "none" ]; then
    echo "Backups disabled - updating PostgreSQL configuration to disable archiving"

    # Update postgresql.conf to disable archiving
    sed -i "s/archive_mode = on/archive_mode = off/" /var/lib/postgresql/data/postgresql.conf
    sed -i "s/archive_command = .*/archive_command = ''/" /var/lib/postgresql/data/postgresql.conf

    echo "PostgreSQL archiving disabled"
else
    # Verify configuration
    if [ -f /etc/pgbackrest/pgbackrest.conf ]; then
        echo "Configuration found and ready"
        cat /etc/pgbackrest/pgbackrest.conf
    else
        echo "WARNING: pgBackRest configuration not yet available"
        echo "It will be generated by the setup service"
    fi
fi

echo "pgBackRest configured successfully!"
