#!/bin/bash
# Install pgBackRest in PostgreSQL container
# This script runs during container initialization

set -e

echo "Configuring pgBackRest in PostgreSQL container..."

# Create necessary directories
mkdir -p /var/lib/pgbackrest/archive \
         /var/lib/pgbackrest/backup \
         /var/log/pgbackrest \
         /var/spool/pgbackrest

# Set permissions for cross-container access
# Use 777 to allow both postgres (UID 999) and backup container (root) to access
chmod -R 777 /var/lib/pgbackrest
chmod -R 777 /var/spool/pgbackrest
chmod -R 755 /var/log/pgbackrest

# Link our mounted config to /etc/pgbackrest
echo "Linking pgBackRest configuration from shared volume..."
if [ -e /etc/pgbackrest ] && [ ! -L /etc/pgbackrest ]; then
    # If it exists and is not a symlink, try to remove it
    rm -rf /etc/pgbackrest 2>/dev/null || {
        echo "Cannot remove existing /etc/pgbackrest, attempting to work around..."
        # If we can't remove it, just ensure the config directory exists
        mkdir -p /pgbackrest-config
    }
fi
# Only create symlink if it doesn't already exist
if [ ! -e /etc/pgbackrest ]; then
    ln -s /pgbackrest-config /etc/pgbackrest
fi

# Check if backups are disabled
if [[ "${PGBACKREST_REPO1_TYPE:-none}" = "none" ]]; then
    echo "Backups disabled - updating PostgreSQL configuration to disable archiving"

    # Update postgresql.conf to disable archiving
    sed -i "s/archive_mode = on/archive_mode = off/" /var/lib/postgresql/data/postgresql.conf
    sed -i "s/archive_command = .*/archive_command = ''/" /var/lib/postgresql/data/postgresql.conf

    echo "PostgreSQL archiving disabled"
else
    # Verify configuration
    if [[ -f /etc/pgbackrest/pgbackrest.conf ]]; then
        echo "Configuration found and ready"
        cat /etc/pgbackrest/pgbackrest.conf
    else
        echo "WARNING: pgBackRest configuration not yet available"
        echo "It will be generated by the setup service"
    fi
fi

echo "pgBackRest configured successfully!"
