services:
  app:
    build:
      context: ../..
      dockerfile: .docker/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-salespider}-app
    environment:
      # Application Environment
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${APP_PORT:-3000}
      - HOSTNAME=0.0.0.0

      # Database Configuration
      - DATABASE_URL=${DATABASE_URL}
      - BACKUP_DATABASE_URL=${BACKUP_DATABASE_URL:-}

      # Security
      - JWT_SECRET=${JWT_SECRET}
      - APP_URL=${APP_URL:-https://${DOMAIN:-localhost}}

      # Application Settings
      - SUPER_ADMIN_EMAIL=${SUPER_ADMIN_EMAIL:-admin@localhost}
      - SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD}
      - LOG_LEVEL=${LOG_LEVEL:-info}

      # Feature Flags
      - ENABLE_ANALYTICS=${ENABLE_ANALYTICS:-false}
      - ENABLE_REPORTS=${ENABLE_REPORTS:-true}
      - ENABLE_BARCODE_SCANNER=${ENABLE_BARCODE_SCANNER:-true}
      - OFFLINE_MODE=${OFFLINE_MODE:-true}

      # Performance Settings
      - DATABASE_POOL_SIZE=${DATABASE_POOL_SIZE:-10}
      - DATABASE_TIMEOUT=${DATABASE_TIMEOUT:-30000}
      - CACHE_TTL=${CACHE_TTL:-3600}

      # SSL Configuration
      - SSL_ENABLED=${SSL_ENABLED:-true}
      - FORCE_HTTPS=${FORCE_HTTPS:-true}

      # GEMINI API KEY
      - GEMINI_API_KEY=${GEMINI_API_KEY}

    volumes:
      - app-uploads:/app/uploads
      - app-logs:/app/logs

    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://127.0.0.1:${APP_PORT:-3000}/api/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: ${APP_MEMORY_LIMIT:-2G}
          cpus: '${APP_CPU_LIMIT:-2.0}'
        reservations:
          memory: ${APP_MEMORY_RESERVATION:-1G}
          cpus: '${APP_CPU_RESERVATION:-1.0}'

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

    networks:
      - salespider-net

volumes:
  app-uploads:
    external: true
  app-logs:
    external: true

networks:
  salespider-net:
    external: true
