services:
  proxy:
    image: caddy:2-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-salespider}-proxy
    
    environment:
      # Domain Configuration
      - DOMAIN=${DOMAIN:-localhost}
      - HOST_IP=${HOST_IP:-127.0.0.1}
      - APP_URL=http://app:${APP_PORT:-3000}
      
      # SSL Configuration
      - SSL_ENABLED=${SSL_ENABLED:-true}
      - FORCE_HTTPS=${FORCE_HTTPS:-true}
      
      # Security Headers
      - SECURITY_HEADERS=${SECURITY_HEADERS:-true}
      - HSTS_ENABLED=${HSTS_ENABLED:-true}
      - HSTS_MAX_AGE=${HSTS_MAX_AGE:-31536000}
      
      # Rate Limiting
      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-true}
      - RATE_LIMIT_REQUESTS=${RATE_LIMIT_REQUESTS:-100}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-1m}
      
      # Logging
      - ACCESS_LOG_ENABLED=${ACCESS_LOG_ENABLED:-true}
      - ERROR_LOG_ENABLED=${ERROR_LOG_ENABLED:-true}
    
    volumes:
      - ../config/proxy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${DATA_PATH:-../data}/ssl:/etc/caddy/certs:ro
      - proxy-data:/data
      - proxy-config:/config
      - app-logs:/var/log/caddy
    
    ports:
      - "0.0.0.0:${HTTP_PORT:-80}:80"
      - "0.0.0.0:${HTTPS_PORT:-443}:443"
    
    healthcheck:
      test: ["CMD", "caddy", "validate", "--config", "/etc/caddy/Caddyfile"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    restart: unless-stopped
    
    deploy:
      resources:
        limits:
          memory: ${PROXY_MEMORY_LIMIT:-512M}
          cpus: '${PROXY_CPU_LIMIT:-0.5}'
        reservations:
          memory: ${PROXY_MEMORY_RESERVATION:-256M}
          cpus: '${PROXY_CPU_RESERVATION:-0.25}'
    
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    
    networks:
      - salespider-net

volumes:
  proxy-data:
    external: true
  proxy-config:
    external: true
  app-logs:
    external: true

networks:
  salespider-net:
    external: true
