services:
  setup:
    image: alpine:latest
    container_name: ${COMPOSE_PROJECT_NAME:-salespider}-setup

    environment:
      # Database Configuration
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-salespider}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      # Application Configuration
      - SUPER_ADMIN_EMAIL=${SUPER_ADMIN_EMAIL:-admin@salespider.local}
      - SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD}
      - APP_URL=${APP_URL:-https://${DOMAIN:-salespider.local}}

      # SSL Configuration
      - DOMAIN=${DOMAIN:-salespider.local}
      - HOST_IP=${HOST_IP:-127.0.0.1}
      - CERT_DAYS=${CERT_DAYS:-3650}

    volumes:
      - ../scripts:/scripts:ro
      - ${DATA_PATH:-../data}/ssl:/ssl
      - app-logs:/logs

    command: |
      sh -c '
        set -e
        echo "Starting SaleSpider setup..."

        # Install required packages
        apk add --no-cache postgresql-client openssl

        # Wait for PostgreSQL to be ready
        echo "Waiting for PostgreSQL to be ready..."
        until pg_isready -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" -U "$POSTGRES_USER"; do
          echo "PostgreSQL is unavailable - sleeping"
          sleep 2
        done

        echo "PostgreSQL is ready - executing setup scripts"

        # Run database setup
        if [ -f /scripts/setup/setup-database.sh ]; then
          echo "Setting up database..."
          sh /scripts/setup/setup-database.sh
        fi

        # Run SSL setup
        if [ -f /scripts/setup/setup-ssl.sh ]; then
          echo "Setting up SSL certificates..."
          sh /scripts/setup/setup-ssl.sh
        fi

        echo "Setup completed successfully"
        touch /logs/setup-completed

        if [ "$KEEP_RUNNING" = "true" ]; then
          tail -f /dev/null
        fi
      '

    restart: "no"

    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
        reservations:
          memory: 128M
          cpus: "0.25"

    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"

    networks:
      - salespider-net

volumes:
  app-logs:

networks:
  salespider-net:
    external: true
