name: Code Quality

on:
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  # 🧪 Job 1: Run tests & analysis
  code-quality:
    runs-on: ubuntu-latest
    outputs:
      result-file: test-results.md
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npx tsc --noEmit

      - name: Check code formatting
        run: npx prettier --check "src/**/*.{ts,tsx,js,jsx,json,md}"
        continue-on-error: true

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

      - name: Save test results summary
        run: |
          echo "## 🧪 Test Results" > test-results.md
          echo "" >> test-results.md
          echo "Tests completed successfully! ✅" >> test-results.md
        shell: bash

      - name: Upload artifact (for comment job)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.md

  # 💬 Job 2: Comment on PR (safe for forks)
  comment-results:
    needs: code-quality
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target'
    permissions:
      issues: write
      pull-requests: write
      contents: read

    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Read results
        id: results
        run: |
          body=$(cat test-results.md)
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$body" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.BODY
            });
        env:
          BODY: ${{ steps.results.outputs.body }}

  # 🛠️ Job 3: Dependency review
  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target'
    permissions:
      contents: read

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
